# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ame-en-harmonie

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present
        env:
          VITE_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          VITE_API_BASE_URL: ${{ vars.API_BASE_URL }}

      - name: Zip artifact for deployment
        run: zip -r release.zip dist package.json package-lock.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_75947ABEAF5043CDA248C4C0F09B8E75 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_00D3F690BA5F4B8C83C94160B2F4A251 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6CF829CCCADB4F4CB722A6D3DC2DEDB7 }}

      - name: Set Azure App Settings
        run: |
          az webapp config appsettings set \
            --name ame-en-harmonie \
            --resource-group rsg_ame-en-harmonie \
            --settings "VITE_SECRET_KEY=${{ secrets.SECRET_KEY }}" "VITE_API_BASE_URL=${{ vars.API_BASE_URL }}" 

            # 🔹 Install serve globally
      - name: Install serve
        run: npm install -g serve

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ame-en-harmonie"
          slot-name: "Production"
          package: .
